---
name: Build and Push Autogen Studio Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/autogenstudio/**/*.json'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Login to Docker Hub
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pre-build autogen studio image
        uses: devcontainers/ci@a56d055efecd725e8cfe370543b6071b79989cc8
        with:
          subFolder: src/autogenstudio
          imageName: docker.io/robinmordasiewicz/autogenstudio
          cacheFrom: docker.io/robinmordasiewicz/autogenstudio
          push: always
