---
name: Build and Push devcontainer Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/devcontainer/**/*.json'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: build the containers
        run: cd src/devcontainer && devcontainer build --workspace-folder . --platform linux/arm64,linux/amd64 --image-name docker.io/robinmordasiewicz/devcontainer:latest --output type=docker
      
      - name: docker push
        run: docker push docker.io/robinmordasiewicz/devcontainer:latest

